apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: repositorio-con-templates
spec:
  type: url
  targets:
    - ./template1-create-repo/template.yaml
    - ./template2-pull-edit-push1/template.yaml
    #- ./template-cookiecutter/template.yaml
