apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: repositorio-con-templates
spec:
  targets:
    - ./tree/main/template1-create-repo/template.yaml
    - ./tree/main/template-basico/template.yaml
    - ./tree/main/template-cookiecutter/template.yaml
