apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-ec2-instance1
  title: Create a new EC2 instance
  description: This template UI asks user for config and creates a new EC2 instance in AWS.
spec:
  owner: jbrunocas-design
  type: documentation

  parameters:
    - title: EC2 instance
      required:
        - instanceName
        - region
        - repoDestination
      properties:
        instanceName:
          title: EC2 Instance Name
          type: string
          enum:
            - us-east-1
            - us-west-2
            - eu-central-1
          description: Name of the EC2 instance to be created.
        region:
          title: AWS Region
          type: string
        features:
          title: Features to Enable
          type: array
          items:
            type: string
            enum:
              - EC2
              - S3
              - RDS
          uniqueItems: true
          description: Select one or more features to enable.
        repoDestination:
          title: New Repository
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
              - gitlab.com
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              additionalScopes:
                github:
                  - repo
                  - workflow
                gitlab:
                  - api
                  - read_user
                  - write_repository
        
  steps:
    - id: fetchBase
      name: Fetch base repo
      action: fetch:plain
      input:
        url: https://github.com/jbrunocas-design/template-1/tree/main
        targetPath: "./"
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
