apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-readme-create-repo
  title: Create a README and push to new remote repo.
  description: Input the name of a new remote repository, modify the content of the README and it will create it.
spec:
  owner: jbrunocas-design
  type: documentation

  parameters:
    - title: Repo Info
      required:
        - repoUrl
      properties:
        repoUrl:
          title: New repository name
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
              - gitlab.com
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              additionalScopes:
                github:
                  - repo
        content:
          title: README Content
          type: string
          description: The content to include in the README file.
          ui:widget: textarea
          ui:options:
            rows: 8
          default: |
            ## About

            This is a simple README file generated by the template.

            ## Usage

            Feel free to modify this README file as needed.

  steps:
    - id: fetch-readme
      name: Fetch README
      action: fetch:template
      input:
        url: ./for-repo
        values:
          content: ${{ parameters.content }}
    - id: publish
      name: Publish to GitHub

      # For creating a new repo and add files.
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        token: ${{ secrets.USER_OAUTH_TOKEN }} 
        
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
